[project]
name = "UniversityPythonHomework"
version = "0.1.0"

[tool.ruff.lint]
select = ["E", "W", "F", "I", "N", "B", "C4", "UP"]
ignore = ["E501"]
line-length = 120

[tool.ruff.lint.isort]
known-first-party = []

[tool.ruff.format]
indent-style = "space"
indent-width = 4
line-length = 120
closing-bracket-alignment = true
space-around-operators = true
